name: 'Publish'
on:
  push:
    tags:
      - 'v*'
jobs:
  release:
    name: 'Publish'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Get tag
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/v/}
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
          registry-url: 'https://npm.pkg.github.com'
      - run: yarn install --frozen-lockfile
      - run: yarn version --no-git-tag-version  --new-version ${{steps.get_version.outputs.VERSION}}
      - name: Publish
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
